import { toHnkIr } from "./parser.mjs";
import { encodeBytecode, bytecodeToBinaryString } from "./bytecode.mjs";

export { canonicalIrJson } from "./canonical-ir.mjs";

export function lowerToJavaScript(ast) {
  const ir = toHnkIr(ast);
  return [
    `// generated by haKodan ${ir.version}`,
    `export const world = ${JSON.stringify(ir.world, null, 2)};`,
    ""
  ].join("\n");
}

export function lowerToBinary(ast) {
  return encodeBytecode(ast);
}

export function binaryString(ast) {
  return bytecodeToBinaryString(lowerToBinary(ast));
}
