import { toHnkIr } from "./parser.mjs";

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map(key => [key, stable(value[key])]));
  }
  return value;
}

export function canonicalIrJson(ast) {
  return JSON.stringify(stable(toHnkIr(ast)));
}

export function lowerToJavaScript(ast) {
  const ir = toHnkIr(ast);
  return [
    `// generated by haKodan ${ir.version}`,
    `export const world = ${JSON.stringify(ir.world, null, 2)};`,
    ""
  ].join("\n");
}

export function lowerToBinary(ast) {
  return new TextEncoder().encode(canonicalIrJson(ast));
}

export function binaryString(ast) {
  return Array.from(lowerToBinary(ast), byte => byte.toString(2).padStart(8, "0")).join("");
}
