import test from "node:test";
import assert from "node:assert/strict";
import { evaluateFormula } from "../src/derived-formula-state.mjs";
import { deriveStat } from "../src/derived-dependency-state.mjs";
import { createWorldRuntime } from "../src/world-runtime.mjs";
const values={negative:-4.6,positive:4.6,health:75,attack:12};const context={resolveStat:stat=>{if(!Object.prototype.hasOwnProperty.call(values,stat))throw new Error(`UNEXPECTED_STAT_RESOLUTION: ${stat}`);return values[stat];}};
test("V2-24 unary functions remain deterministic",()=>{assert.equal(evaluateFormula({op:"ABS",args:[{stat:"negative"}]},context).value,4.6);assert.equal(evaluateFormula({op:"ROUND",args:[{stat:"positive"}]},context).value,5);assert.equal(evaluateFormula({op:"FLOOR",args:[{stat:"positive"}]},context).value,4);assert.equal(evaluateFormula({op:"CEIL",args:[{stat:"positive"}]},context).value,5);});
for(const[op,l,r,e]of[["GT",3,2,true],["GTE",2,2,true],["LT",2,3,true],["LTE",2,2,true],["EQ",2,2,true],["EQ",2,3,false]])test(`V2-24 ${op} comparison resolves declaratively`,()=>{const x=evaluateFormula({op:"IF",condition:{op,left:{value:l},right:{value:r}},then:{value:1},else:{value:0}},context);assert.equal(x.value,e?1:0);assert.equal(x.condition.result,e);});
test("V2-24 IF is lazy for unselected branches",()=>{assert.equal(evaluateFormula({op:"IF",condition:{op:"EQ",left:{value:1},right:{value:0}},then:{stat:"must_not_resolve"},else:{value:7}},context).value,7);assert.equal(evaluateFormula({op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1}},then:{value:7},else:{stat:"must_not_resolve"}},context).value,7);});
test("V2-24 IF evidence never traverses dormant branch accessors",()=>{let touched=0;const dormant={};Object.defineProperty(dormant,"stat",{enumerable:true,get(){touched+=1;throw new Error("DORMANT_BRANCH_TOUCHED");}});const result=evaluateFormula({op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1}},then:{value:7},else:dormant},context);assert.equal(result.value,7);assert.equal(touched,0);});
test("V2-24 parent arithmetic evidence never re-traverses nested IF dormant branch",()=>{let touched=0;const dormant={};Object.defineProperty(dormant,"stat",{enumerable:true,get(){touched+=1;throw new Error("NESTED_DORMANT_BRANCH_TOUCHED");}});const result=evaluateFormula({op:"ADD",args:[{value:1},{op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1}},then:{value:7},else:dormant}]},context);assert.equal(result.value,8);assert.equal(touched,0);});
test("V2-24 parent unary evidence tolerates uncloneable nested IF dormant branch",()=>{const result=evaluateFormula({op:"ABS",args:[{op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1}},then:{value:-7},else:{stat:"unused",callback:()=>99}}]},context);assert.equal(result.value,7);});
test("V2-24 IF requires both branches",()=>{assert.throws(()=>evaluateFormula({op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1}},then:{value:1}},context),/HAKODAN_DERIVED_FORMULA_INVALID/);});
test("V2-24 exact-key security remains closed",()=>assert.throws(()=>evaluateFormula({op:"IF",condition:{op:"EQ",left:{value:1},right:{value:1},callback:()=>true},then:{value:1},else:{value:0}},context),/HAKODAN_DERIVED_CONDITION_INVALID/));
test("V2-24 legacy V2-23 arithmetic behavior remains unchanged",()=>{assert.equal(evaluateFormula({op:"ADD",args:[{value:2},{value:3}]},context).value,5);assert.throws(()=>evaluateFormula({op:"DIVIDE",args:[{value:1},{value:0}]},context),/HAKODAN_DERIVED_FORMULA_DIVIDE_BY_ZERO/);});
const subject=()=>({stats:{base:{health:75,attack:12},definitions:{},derived:{}},equipment:{main_hand:null}});
test("V2-24 selected cycle rejects while unselected cycle stays dormant",()=>{const a=subject();a.stats.definitions={power:{formula:{op:"IF",condition:{op:"GTE",left:{stat:"health"},right:{value:50}},then:{stat:"combat"},else:{value:0}}},combat:{formula:{stat:"power"}}};assert.throws(()=>deriveStat(a,"stats.base","stats.definitions","equipment","power"),/HAKODAN_DERIVED_CYCLE/);const b=subject();b.stats.definitions={power:{formula:{op:"IF",condition:{op:"LT",left:{stat:"health"},right:{value:50}},then:{stat:"combat"},else:{value:7}}},combat:{formula:{stat:"power"}}};assert.equal(deriveStat(b,"stats.base","stats.definitions","equipment","power").value,7);});
function runtime(actions){return createWorldRuntime({ir:"HNK-IR",version:"0.2.0",world:{entities:[{id:"alakazam",properties:subject()}],rules:[{id:"v2-24",trigger:"tick",condition:{kind:"DERIVED_GTE",subject:"alakazam",basePath:"stats.base",definitionsPath:"stats.definitions",equipmentPath:"equipment",stat:"power",value:15},actions}]}});}
test("V2-24 runtime sync materializes conditional evidence",()=>{const r=runtime([{kind:"SYNC_DERIVED_STATS",subject:"alakazam",basePath:"stats.base",definitionsPath:"stats.definitions",equipmentPath:"equipment",derivedPath:"stats.derived"}]),s=r.entity("alakazam");s.stats.definitions={bonus:{formula:{op:"ADD",args:[{stat:"attack"},{value:3}]}},power:{formula:{op:"IF",condition:{op:"GTE",left:{stat:"health"},right:{value:50}},then:{stat:"bonus"},else:{value:0}}}};const[e]=r.tick();assert.equal(s.stats.derived.power,15);assert.equal(e.derived.power.formula.selected,"then");});
