import test from "node:test";
import assert from "node:assert/strict";
import { collectEquipmentEffects, deriveStat, deriveStats } from "../src/equipment-effects-state.mjs";
import { createCanonicalRuntimeRegistries } from "../src/runtime-capability-registry.mjs";
import { createWorldRuntime } from "../src/world-runtime.mjs";

const excalibur=()=>({id:"sword",instanceId:"excalibur-001",quantity:1,slot:"main_hand",effects:[{stat:"attack",op:"ADD",value:7}]});
const subject=()=>({stats:{base:{attack:10,defense:4},derived:{}},equipment:{main_hand:excalibur(),off_hand:null,head:null,body:null}});

test("V2-21 Excalibur derives attack 10 to 17 without mutating base stats",()=>{const s=subject();const before=structuredClone(s.stats.base);const result=deriveStat(s,"stats.base","equipment","attack");assert.equal(result.value,17);assert.equal(result.base,10);assert.deepEqual(s.stats.base,before);});
test("V2-21 unequipped item contributes no effects",()=>{const s=subject();s.equipment.main_hand=null;assert.equal(deriveStat(s,"stats.base","equipment","attack").value,10);});
test("V2-21 multiple equipped modifiers compose in deterministic canonical slot order",()=>{const s=subject();s.equipment.off_hand={id:"focus",instanceId:"focus-001",quantity:1,slot:"off_hand",effects:[{stat:"attack",op:"ADD",value:3},{stat:"attack",op:"SUBTRACT",value:2}]};const result=deriveStat(s,"stats.base","equipment","attack");assert.equal(result.value,18);assert.deepEqual(result.modifiers.map(x=>[x.slot,x.op,x.value]),[["main_hand","ADD",7],["off_hand","ADD",3],["off_hand","SUBTRACT",2]]);});
test("V2-21 effect order is canonical even when equipment object insertion order differs",()=>{const s={stats:{base:{attack:10}},equipment:{off_hand:{id:"focus",instanceId:"focus-001",quantity:1,slot:"off_hand",effects:[{stat:"attack",op:"SUBTRACT",value:2}]},main_hand:{...excalibur()}}};const result=deriveStat(s,"stats.base","equipment","attack");assert.deepEqual(result.modifiers.map(x=>[x.slot,x.op,x.value]),[["main_hand","ADD",7],["off_hand","SUBTRACT",2]]);assert.equal(result.value,15);});
test("V2-21 effect collection is deterministic and carries ownership evidence",()=>{const effects=collectEquipmentEffects(subject(),"equipment");assert.deepEqual(effects,[{slot:"main_hand",instanceId:"excalibur-001",id:"sword",effectIndex:0,stat:"attack",op:"ADD",value:7}]);});
test("V2-21 derives all numeric base stats while preserving unaffected stats",()=>{const result=deriveStats(subject(),"stats.base","equipment");assert.equal(result.attack.value,17);assert.equal(result.defense.value,4);});
test("V2-21 invalid numeric modifier rejects explicitly",()=>{const s=subject();s.equipment.main_hand.effects[0].value="7";assert.throws(()=>deriveStat(s,"stats.base","equipment","attack"),/HAKODAN_EFFECT_NUMERIC_VALUE_REQUIRED: attack/);});
test("V2-21 unsupported modifier operation rejects explicitly",()=>{const s=subject();s.equipment.main_hand.effects[0].op="MULTIPLY";assert.throws(()=>deriveStat(s,"stats.base","equipment","attack"),/HAKODAN_EFFECT_UNSUPPORTED_OP: MULTIPLY/);});
test("V2-21 missing base stat rejects explicitly",()=>{assert.throws(()=>deriveStat(subject(),"stats.base","equipment","magic"),/HAKODAN_BASE_STAT_NOT_FOUND: magic/);});
test("V2-21 nonnumeric base stat rejects explicitly",()=>{const s=subject();s.stats.base.attack="10";assert.throws(()=>deriveStat(s,"stats.base","equipment","attack"),/HAKODAN_BASE_STAT_NUMERIC_REQUIRED: attack/);});

test("V2-21 registry exposes derived-stat runtime capabilities",()=>{const{conditions,actions}=createCanonicalRuntimeRegistries();for(const k of ["DERIVED_GT","DERIVED_GTE","DERIVED_LT","DERIVED_LTE"])assert.equal(conditions.has(k),true);assert.equal(actions.has("SYNC_DERIVED_STATS"),true);});
function runtime(condition,actions){return createWorldRuntime({ir:"HNK-IR",version:"0.2.0",world:{entities:[{id:"alakazam",properties:subject()}],rules:[{id:"derived-rule",trigger:"tick",condition,actions}]}});}
test("V2-21 DERIVED_GTE reads pure derived attack without mutating base or derived state",()=>{const r=runtime({kind:"DERIVED_GTE",subject:"alakazam",basePath:"stats.base",equipmentPath:"equipment",stat:"attack",value:15},[]);const before=structuredClone(r.entity("alakazam").stats);assert.deepEqual(r.tick(),[]);assert.deepEqual(r.entity("alakazam").stats,before);});
test("V2-21 SYNC_DERIVED_STATS writes only derived target and emits ordered evidence",()=>{const r=runtime({kind:"DERIVED_GTE",subject:"alakazam",basePath:"stats.base",equipmentPath:"equipment",stat:"attack",value:15},[{kind:"SYNC_DERIVED_STATS",subject:"alakazam",basePath:"stats.base",equipmentPath:"equipment",derivedPath:"stats.derived"}]);const[e]=r.tick();assert.equal(r.entity("alakazam").stats.base.attack,10);assert.equal(r.entity("alakazam").stats.derived.attack,17);assert.deepEqual(e.derived.attack,{stat:"attack",base:10,modifiers:[{slot:"main_hand",instanceId:"excalibur-001",id:"sword",effectIndex:0,stat:"attack",op:"ADD",value:7}],value:17});});
test("V2-21 derived conditions gate runtime deterministically",()=>{const r=runtime({kind:"DERIVED_LT",subject:"alakazam",basePath:"stats.base",equipmentPath:"equipment",stat:"attack",value:15},[{kind:"SET",subject:"alakazam",path:"marker",value:"should-not-run"}]);assert.deepEqual(r.tick(),[]);assert.equal(r.entity("alakazam").marker,undefined);});
