import test from "node:test";
import assert from "node:assert/strict";
import { equipItemInstance, unequipItemInstance, isInstanceEquipped, isEquipmentSlotEmpty } from "../src/equipment-state.mjs";
import { createCanonicalRuntimeRegistries } from "../src/runtime-capability-registry.mjs";
import { createWorldRuntime } from "../src/world-runtime.mjs";

const sword=()=>({id:"sword",instanceId:"excalibur-001",quantity:1,slot:"main_hand",durability:87,enchantment:"light"});
const hero=()=>({inventory:{items:[sword()]},equipment:{main_hand:null,off_hand:null,head:null,body:null}});

test("V2-20 equips exact owned instance into compatible empty slot",()=>{const h=hero();const e=equipItemInstance(h,"inventory.items","equipment","excalibur-001","main_hand");assert.deepEqual(h.inventory.items,[]);assert.deepEqual(h.equipment.main_hand,sword());assert.equal(e.instanceId,"excalibur-001");});
test("V2-20 occupied slot rejects before mutation",()=>{const h=hero();h.equipment.main_hand={id:"dagger",instanceId:"dagger-001",quantity:1,slot:"main_hand"};const before=structuredClone(h);assert.throws(()=>equipItemInstance(h,"inventory.items","equipment","excalibur-001","main_hand"),/HAKODAN_EQUIPMENT_SLOT_OCCUPIED/);assert.deepEqual(h,before);});
test("V2-20 incompatible slot rejects before mutation",()=>{const h=hero();const before=structuredClone(h);assert.throws(()=>equipItemInstance(h,"inventory.items","equipment","excalibur-001","off_hand"),/HAKODAN_EQUIPMENT_SLOT_INCOMPATIBLE/);assert.deepEqual(h,before);});
test("V2-20 unequip returns exact instance with metadata preserved",()=>{const h=hero();equipItemInstance(h,"inventory.items","equipment","excalibur-001","main_hand");const e=unequipItemInstance(h,"equipment","main_hand","inventory.items");assert.deepEqual(h.inventory.items,[sword()]);assert.equal(h.equipment.main_hand,null);assert.deepEqual(e.item,sword());});
test("V2-20 equipment predicates are deterministic",()=>{const h=hero();assert.equal(isEquipmentSlotEmpty(h,"equipment","main_hand"),true);assert.equal(isInstanceEquipped(h,"equipment","excalibur-001"),false);equipItemInstance(h,"inventory.items","equipment","excalibur-001","main_hand");assert.equal(isEquipmentSlotEmpty(h,"equipment","main_hand"),false);assert.equal(isInstanceEquipped(h,"equipment","excalibur-001"),true);});

test("V2-20 registry exposes equipment capabilities",()=>{const{conditions,actions}=createCanonicalRuntimeRegistries();for(const k of ["IS_EQUIPPED","SLOT_EMPTY"])assert.equal(conditions.has(k),true);for(const k of ["EQUIP_INSTANCE","UNEQUIP_INSTANCE"])assert.equal(actions.has(k),true);});
function runtime(actions,condition={kind:"SLOT_EMPTY",subject:"alakazam",equipmentPath:"equipment",slot:"main_hand"}){return createWorldRuntime({ir:"HNK-IR",version:"0.2.0",world:{entities:[{id:"alakazam",properties:hero()}],rules:[{id:"equipment-rule",trigger:"tick",condition,actions}]}});}
test("V2-20 runtime equips Excalibur and emits deterministic evidence",()=>{const r=runtime([{kind:"EQUIP_INSTANCE",subject:"alakazam",path:"inventory.items",equipmentPath:"equipment",instanceId:"excalibur-001",slot:"main_hand"}]);const[e]=r.tick();assert.deepEqual(r.entity("alakazam").inventory.items,[]);assert.deepEqual(r.entity("alakazam").equipment.main_hand,sword());assert.equal(e.action,"EQUIP_INSTANCE");assert.equal(e.instanceId,"excalibur-001");assert.equal(e.slot,"main_hand");assert.deepEqual(e.item,sword());});
test("V2-20 IS_EQUIPPED gates unequip and preserves ownership evidence",()=>{const r=runtime([{kind:"EQUIP_INSTANCE",subject:"alakazam",path:"inventory.items",equipmentPath:"equipment",instanceId:"excalibur-001",slot:"main_hand"}]);r.tick();r.rules[0].condition={kind:"IS_EQUIPPED",subject:"alakazam",equipmentPath:"equipment",instanceId:"excalibur-001"};r.rules[0].actions=[{kind:"UNEQUIP_INSTANCE",subject:"alakazam",equipmentPath:"equipment",slot:"main_hand",path:"inventory.items"}];const evidence=r.tick();assert.deepEqual(r.entity("alakazam").inventory.items,[sword()]);assert.equal(r.entity("alakazam").equipment.main_hand,null);assert.equal(evidence.at(-1).action,"UNEQUIP_INSTANCE");assert.equal(evidence.at(-1).instanceId,"excalibur-001");});
test("V2-20 runtime occupied slot fails atomically with no new evidence",()=>{const r=runtime([{kind:"EQUIP_INSTANCE",subject:"alakazam",path:"inventory.items",equipmentPath:"equipment",instanceId:"excalibur-001",slot:"main_hand"}],{kind:"HAS_INSTANCE",subject:"alakazam",path:"inventory.items",instanceId:"excalibur-001"});r.entity("alakazam").equipment.main_hand={id:"dagger",instanceId:"dagger-001",quantity:1,slot:"main_hand"};assert.throws(()=>r.tick(),/HAKODAN_EQUIPMENT_SLOT_OCCUPIED/);assert.deepEqual(r.changes,[]);assert.deepEqual(r.entity("alakazam").inventory.items,[sword()]);});
