import test from "node:test";
import assert from "node:assert/strict";
import { createCanonicalRuntimeRegistries } from "../src/runtime-capability-registry.mjs";
import { itemCount, addItem, removeItem, transferItem } from "../src/item-stack-state.mjs";

test("V2-17 registry exposes item stack capabilities",()=>{const{conditions,actions}=createCanonicalRuntimeRegistries();for(const kind of ["HAS_ITEM","ITEM_COUNT"])assert.equal(conditions.has(kind),true);for(const kind of ["ADD_ITEM","REMOVE_ITEM","TRANSFER_ITEM"])assert.equal(actions.has(kind),true);});
test("V2-17 item count is deterministic",()=>{const s={inventory:{items:[{id:"potion",quantity:5}]}};assert.equal(itemCount(s,"inventory.items","potion"),5);assert.equal(itemCount(s,"inventory.items","gem"),0);});
test("V2-17 add creates and increments stacks",()=>{const s={inventory:{items:[]}};addItem(s,"inventory.items","potion",2);addItem(s,"inventory.items","potion",3);assert.deepEqual(s.inventory.items,[{id:"potion",quantity:5}]);});
test("V2-17 remove decrements and removes zero stack",()=>{const s={inventory:{items:[{id:"potion",quantity:5}]}};removeItem(s,"inventory.items","potion",3);assert.deepEqual(s.inventory.items,[{id:"potion",quantity:2}]);removeItem(s,"inventory.items","potion",2);assert.deepEqual(s.inventory.items,[]);});
test("V2-17 insufficient quantity is explicit and inert",()=>{const s={inventory:{items:[{id:"potion",quantity:1}]}};assert.throws(()=>removeItem(s,"inventory.items","potion",2),/HAKODAN_ITEM_INSUFFICIENT_QUANTITY/);assert.deepEqual(s.inventory.items,[{id:"potion",quantity:1}]);});
test("V2-17 transfers requested quantity atomically",()=>{const chest={inventory:{items:[{id:"potion",quantity:5}]}};const alakazam={inventory:{items:[]}};const e=transferItem(chest,"inventory.items",alakazam,"inventory.items","potion",2);assert.deepEqual(chest.inventory.items,[{id:"potion",quantity:3}]);assert.deepEqual(alakazam.inventory.items,[{id:"potion",quantity:2}]);assert.equal(e.quantity,2);assert.deepEqual(e.sourceBefore,[{id:"potion",quantity:5}]);assert.deepEqual(e.targetAfter,[{id:"potion",quantity:2}]);});
test("V2-17 rejects invalid quantities",()=>{const s={inventory:{items:[]}};for(const q of [-1,1.5,NaN,Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>addItem(s,"inventory.items","potion",q),/HAKODAN_ITEM_QUANTITY_INVALID/);});
test("V2-17 duplicate item ids fail explicitly",()=>{const s={inventory:{items:[{id:"potion",quantity:1},{id:"potion",quantity:2}]}};assert.throws(()=>itemCount(s,"inventory.items","potion"),/HAKODAN_ITEM_DUPLICATE_ID/);});
test("V2-17 failed transfer does not partially mutate either inventory",()=>{const chest={inventory:{items:[{id:"potion",quantity:1}]}};const alakazam={inventory:{items:[{id:"gem",quantity:2}]}};assert.throws(()=>transferItem(chest,"inventory.items",alakazam,"inventory.items","potion",2),/HAKODAN_ITEM_INSUFFICIENT_QUANTITY/);assert.deepEqual(chest.inventory.items,[{id:"potion",quantity:1}]);assert.deepEqual(alakazam.inventory.items,[{id:"gem",quantity:2}]);});
test("V2-17 transfer preserves source metadata when creating target stack",()=>{const chest={inventory:{items:[{id:"potion",quantity:5,rarity:"rare",effect:"heal"}]}};const alakazam={inventory:{items:[]}};transferItem(chest,"inventory.items",alakazam,"inventory.items","potion",2);assert.deepEqual(alakazam.inventory.items,[{id:"potion",quantity:2,rarity:"rare",effect:"heal"}]);});
test("V2-17 quantity addition cannot exceed safe deterministic integer range",()=>{const s={inventory:{items:[{id:"potion",quantity:Number.MAX_SAFE_INTEGER}]}};assert.throws(()=>addItem(s,"inventory.items","potion",1),/HAKODAN_ITEM_QUANTITY_INVALID/);assert.equal(s.inventory.items[0].quantity,Number.MAX_SAFE_INTEGER);});
