import test from "node:test";
import assert from "node:assert/strict";
import { parse } from "../src/parser.mjs";
import { canonicalIrJson, lowerToJavaScript, lowerToBinary, binaryString } from "../src/lowering.mjs";

const pt = `mundo AbraIsland {
  entidade Alakazam { propriedade vida = 100 }
  evento Despertar { ação despertar("Alakazam") }
}`;

const en = `world AbraIsland {
  entity Alakazam { property vida = 100 }
  event Despertar { action despertar("Alakazam") }
}`;

test("lowering é semanticamente idêntico em PT-BR e EN", () => {
  const a = parse(pt, { profile: "PT-BR" });
  const b = parse(en, { profile: "EN" });
  assert.equal(canonicalIrJson(a), canonicalIrJson(b));
  assert.equal(lowerToJavaScript(a), lowerToJavaScript(b));
  assert.deepEqual(lowerToBinary(a), lowerToBinary(b));
});

test("haKodan produz representação binária determinística", () => {
  const ast = parse(pt, { profile: "PT-BR" });
  const bytes = lowerToBinary(ast);
  assert.ok(bytes.length > 0);
  assert.match(binaryString(ast), /^[01]+$/);
  assert.equal(binaryString(ast).length, bytes.length * 8);
});

test("JavaScript target preserva world HNK-IR", () => {
  const js = lowerToJavaScript(parse(pt, { profile: "PT-BR" }));
  assert.match(js, /generated by haKodan/);
  assert.match(js, /AbraIsland/);
  assert.match(js, /Alakazam/);
});
